/**
 * 起床战争违规申诉 模块
 * 包含中英双语申诉协议内容，供文档页渲染
 * 依赖：terms.js（提供 window.renderMarkdown）
 */
(function() {
    'use strict';

    // ========== 中文申诉协议 ==========
    var appealMarkdown = [
        '## 起床战争违规申诉',
        '',
        '> 最后更新：2026年7月',
        '',
        '---',
        '',
        '### 一、协议核心逻辑',
        '',
        '本申诉协议基于现代网络安全"零信任架构"设计，旨在通过标准化的取证流程，确保申诉的客观性与公正性。核心逻辑包含以下三大支柱：',
        '',
        '**1.1 零信任原则**',
        '管理端默认不信任任何口头解释、非结构化截图或未经校验的日志文件。所有申诉必须基于"可验证、可追溯、不可篡改"的原始数据与行为记录。',
        '',
        '**1.2 证据链闭环**',
        '申诉材料必须构成完整的逻辑闭环，覆盖从"启动前"到"被踢出后"的全生命周期：',
        '- **初始状态固化**：证明启动游戏时模组列表的纯净性',
        '- **运行时审计**：证明游戏运行期间无内存注入或异常类名',
        '- **事后保全**：证明日志文件在提交前未被修改',
        '- **物理层验证**：证明操作者为真人，且无硬件宏或虚拟摄像头欺骗',
        '',
        '**1.3 成本博弈机制**',
        '本流程旨在通过标准化的技术手段，极大提高作弊者伪造证据的成本，同时为被误封的真实玩家提供一条清晰、可执行的自证路径。',
        '',
        '---',
        '',
        '### 二、详细取证流程规范',
        '',
        '申诉人需严格按照以下步骤进行操作，任何步骤的缺失或违规均可能导致申诉被驳回。',
        '',
        '**2.1 准备工作**',
        '- **工具下载**：下载并解压官方提供的《哈希校验工具》及《OBS录制预设》',
        '- **时间同步**：确保电脑系统时间、手机时间、游戏内时间三者完全一致（误差不得超过1秒）',
        '- **环境清理**：关闭所有非必要后台程序（如QQ、微信、Discord等），防止弹窗干扰桌面录制',
        '',
        '**2.2 桌面录制与模组列表展示**',
        '- 启动 OBS，加载官方预设，确保录制范围为整个桌面（非游戏窗口）',
        '- 开始录制，鼠标清晰指向桌面右下角，停留3秒以展示系统时间',
        '- 打开游戏启动器，进入版本设置，一镜到底展示 `mods` 文件夹内的所有文件',
        '- 滚动鼠标滚轮，确保所有模组文件名清晰可见，不得剪辑或加速',
        '- 直接点击启动游戏，保持 OBS 持续录制，不得切出桌面',
        '',
        '**2.3 游戏内运行时审计**',
        '- 进入游戏后，立即调出模组自带的类名/UI展示界面（禁止使用控制台指令）',
        '- 在界面中停留5秒，确保关键数据清晰可见',
        '- 正常进行游戏，直至被反作弊系统踢出或管理员封禁',
        '- 被踢出后，不要关闭游戏，直接按 `Alt+Tab` 切回桌面（OBS 需持续录制切屏过程）',
        '',
        '**2.4 日志保全与哈希计算**',
        '- 在桌面录屏中，打开 `.minecraft/logs` 文件夹',
        '- 找到最新的 `latest.log` 文件，将其拖入已打开的《哈希校验工具》窗口',
        '- 等待哈希值生成，鼠标指向结果停留3秒',
        '- 停止 OBS 录制，保存视频文件',
        '',
        '> **注意**：对于OBS录制的视频文件，也建议使用同样的哈希校验工具计算哈希值，以确保证据视频的完整性和未被篡改。',
        '',
        '**2.5 手部双录与时间戳对齐**',
        '- 使用手机或独立摄像头，从侧后方45度角拍摄手部及键盘鼠标操作',
        '- 录制内容必须包含：启动游戏、游戏内操作、被踢出后的切屏及哈希计算全过程',
        '- 视频开头需清晰拍摄手机/电脑屏幕上的时间，用于与 OBS 录屏进行毫秒级时间戳对齐',
        '- 禁止使用虚拟摄像头，禁止后期剪辑',
        '',
        '---',
        '',
        '### 三、申诉邮件标准模板',
        '',
        '完成取证后，请通过电子邮件提交申诉，严禁使用聊天软件发送零散文件。',
        '',
        '**3.1 邮件主题格式**',
        '`【起床战争申诉】账号：[游戏ID] - 违规类型：[如：疑似连点器] - 日期：[YYYY-MM-DD]`',
        '',
        '**3.2 邮件正文模板**',
        '尊敬的 4U4N 管理团队：',
        '您好！',
        '',
        '本人账号 [游戏ID] 于 [被封禁时间] 被判定为 [违规类型]。',
        '本人郑重声明：在此时间段内绝无任何作弊行为。',
        '',
        '为配合服务器"零信任"安全审查，本人已严格按照《终极自证协议》完成全套取证，',
        '现提交以下证据，请予以核查：',
        '',
        '1. 桌面录屏：包含模组列表展示、启动过程、游戏内UI展示、切屏及哈希计算全过程',
        '2. 哈希校验结果：latest.log 的 MD5/SHA256 值为：[填写哈希值]',
        '3. 手部双录视频：已包含时间戳，可与桌面录屏对齐',
        '4. 原始日志文件：latest.log（未做任何修改）',
        '',
        '本人承诺以上材料均为原始、未篡改文件，并愿意接受管理团队的交叉比对与技术审计。',
        '如确系本人操作失误或硬件故障，本人愿意接受服务器的最终裁决。',
        '',
        '感谢查阅！',
        '',
        '申诉人：[真实姓名/常用昵称]',
        '联系方式：[QQ/微信]',
        '提交时间：[YYYY-MM-DD HH:MM]',
        '',
        '**3.3 附件命名规范**',
        '请严格遵守以下命名格式，否则视为无效申诉：',
        '- `附件1_[游戏ID]_桌面录屏.mp4`',
        '- `附件2_[游戏ID]_手部双录.mp4`',
        '- `附件3_[游戏ID]_latest.log`',
        '- `附件4_[游戏ID]_哈希计算结果.txt`（可选，若正文已写可不传）',
        '',
        '---',
        '',
        '### 四、工具使用指南说明',
        '',
        '**4.1 哈希校验工具**',
        '- **用途**：计算文件的"数字指纹"，确保日志文件未被篡改',
        '- **操作**：解压后直接运行，将 `latest.log` 拖入窗口，复制生成的字符串即可',
        '- **注意**：请勿修改工具内的任何配置文件',
        '',
        '**4.2 OBS 录制预设**',
        '- **用途**：确保录制范围、帧率、编码器符合审核标准',
        '- **操作**：在 OBS 中点击"配置文件" → "导入"，选择官方提供的 `.json` 预设文件',
        '- **检查**：导入后请确认"来源"中已包含"显示器采集"及"窗口采集（哈希工具）"',
        '',
        '**4.3 常见问题**',
        '- **Q: 视频时间戳对不上怎么办？**',
        '  A: 重新录制。时间戳对齐是核心审核标准，无法通过后期调整。',
        '- **Q: 模组没有UI展示界面怎么办？**',
        '  A: 请在邮件中说明具体模组名称，管理端将提供替代方案或豁免该条款。',
        '- **Q: 日志文件找不到？**',
        '  A: 检查是否开启了"隐藏已知文件扩展名"，或确认游戏是否成功写入日志。',
        '',
        '> **⚠ 重要提示**：一般在3-7个工作日内完成审核，每次申诉至少间隔3天；连续申诉5次后每次被封禁或踢出，降低申诉优先级并降低可信度；造伪证的且后台有多次检测记录的酌情增加惩罚并停止处理其申诉；证据不全者打回；乱发信息或含有侮辱、威胁性语言的，屏蔽并不予受理。若包含明确对管理组、其他正常玩家的人身攻击，或威胁服务器安全的，将不予处理，加强惩罚，严重者可提起警告或刑事诉讼。',
        '',
        '---',
        '',
        '> 最终解释权归 4U4N 管理团队所有。本协议自发布之日起生效，所有申诉均以此版本为准。'
    ].join('\n');

    // ========== 英文申诉协议 ==========
    var appealMarkdownEn = [
        '## BedWars Violation Appeal',
        '',
        '> Last updated: July 2026',
        '',
        '---',
        '',
        '### I. Core Logic of the Protocol',
        '',
        'This appeal protocol is designed based on the modern cybersecurity "Zero Trust Architecture," aiming to ensure objectivity and fairness through standardized evidence collection procedures. The core logic consists of the following three pillars:',
        '',
        '**1.1 Zero Trust Principle**',
        'The management side does not trust any verbal explanations, unstructured screenshots, or unverified log files by default. All appeals must be based on "verifiable, traceable, and tamper-proof" raw data and behavioral records.',
        '',
        '**1.2 Evidence Chain Closure**',
        'Appeal materials must form a complete logical closed loop, covering the full lifecycle from "before launch" to "after being kicked":',
        '- **Initial State Freeze**: Prove the purity of the mod list at game launch',
        '- **Runtime Audit**: Prove no memory injection or anomalous class names during gameplay',
        '- **Post-Event Preservation**: Prove log files were not modified before submission',
        '- **Physical Layer Verification**: Prove the operator is a real person, with no hardware macros or virtual camera deception',
        '',
        '**1.3 Cost Game Mechanism**',
        'This process aims to dramatically increase the cost of evidence forgery for cheaters through standardized technical means, while providing a clear and actionable self-verification path for genuinely false-banned players.',
        '',
        '---',
        '',
        '### II. Detailed Evidence Collection Process',
        '',
        'The appellant must strictly follow the steps below. Any missing step or violation may result in the appeal being rejected.',
        '',
        '**2.1 Preparation**',
        '- **Tool Download**: Download and extract the official "Hash Verification Tool" and "OBS Recording Preset"',
        '- **Time Synchronization**: Ensure the computer system time, phone time, and in-game time are fully consistent (error must not exceed 1 second)',
        '- **Environment Cleanup**: Close all non-essential background programs (such as QQ, WeChat, Discord, etc.) to prevent pop-ups from disturbing desktop recording',
        '',
        '**2.2 Desktop Recording & Mod List Display**',
        '- Launch OBS, load the official preset, and ensure the recording range is the entire desktop (not just the game window)',
        '- Start recording, clearly point the mouse to the bottom-right corner of the desktop and hold for 3 seconds to show the system time',
        '- Open the game launcher, enter version settings, and show all files in the `mods` folder in one continuous shot',
        '- Scroll the mouse wheel to ensure all mod filenames are clearly visible — no editing or speeding up',
        '- Click to launch the game directly, keep OBS recording continuously, and do not switch out of the desktop',
        '',
        '**2.3 In-Game Runtime Audit**',
        '- Once in-game, immediately bring up the mod\'s built-in class name/UI display interface (console commands are prohibited)',
        '- Stay on the interface for 5 seconds to ensure key data is clearly visible',
        '- Play the game normally until kicked by the anti-cheat system or banned by an admin',
        '- After being kicked, do not close the game — press `Alt+Tab` to switch back to the desktop (OBS must continue recording the switching process)',
        '',
        '**2.4 Log Preservation & Hash Calculation**',
        '- In the desktop recording, open the `.minecraft/logs` folder',
        '- Find the latest `latest.log` file and drag it into the opened "Hash Verification Tool" window',
        '- Wait for the hash value to generate, point the mouse at the result and hold for 3 seconds',
        '- Stop OBS recording and save the video file',
        '',
        '> **Note**: It is also recommended to use the same hash verification tool to calculate the hash value of the OBS-recorded video file, to ensure the integrity and authenticity of the evidence video.',
        '',
        '**2.5 Hand Recording & Timestamp Alignment**',
        '- Use a phone or standalone camera to film your hands and keyboard/mouse operations from a 45-degree angle from the side-rear',
        '- The recording must include: game launch, in-game operations, screen switching after being kicked, and the full hash calculation process',
        '- The beginning of the video must clearly capture the time on the phone/computer screen for millisecond-level timestamp alignment with the OBS recording',
        '- Virtual cameras are prohibited; post-production editing is prohibited',
        '',
        '---',
        '',
        '### III. Appeal Email Standard Template',
        '',
        'After completing evidence collection, please submit your appeal via email. Sending scattered files through chat software is strictly prohibited.',
        '',
        '**3.1 Email Subject Format**',
        '`[BedWars Appeal] Account: [GameID] - Violation Type: [e.g., Suspected Auto-Clicker] - Date: [YYYY-MM-DD]`',
        '',
        '**3.2 Email Body Template**',
        'Dear 4U4N Management Team,',
        'Hello!',
        '',
        'My account [GameID] was determined to have committed [Violation Type]',
        'on [Ban Time]. I solemnly declare: I did not engage in any cheating',
        'behavior during this period.',
        '',
        'To cooperate with the server\'s "Zero Trust" security review, I have',
        'completed the full evidence collection in strict accordance with the',
        '"Ultimate Self-Verification Protocol." I hereby submit the following',
        'evidence for your review:',
        '',
        '1. Desktop Recording: Includes mod list display, launch process,',
        '   in-game UI display, screen switching, and hash calculation',
        '2. Hash Verification Result: MD5/SHA256 value of latest.log: [Enter Hash]',
        '3. Hand Recording Video: Includes timestamps for alignment with desktop recording',
        '4. Original Log File: latest.log (unmodified)',
        '',
        'I promise that all of the above materials are original and unmodified',
        'files, and I am willing to accept cross-comparison and technical',
        'auditing by the management team. If it is indeed my operational error',
        'or hardware failure, I am willing to accept the server\'s final ruling.',
        '',
        'Thank you for your review!',
        '',
        'Appellant: [Real Name / Common Nickname]',
        'Contact: [QQ / WeChat]',
        'Submission Time: [YYYY-MM-DD HH:MM]',
        '',
        '**3.3 Attachment Naming Convention**',
        'Please strictly follow the naming format below, otherwise the appeal will be considered invalid:',
        '- `Attachment1_[GameID]_Desktop_Recording.mp4`',
        '- `Attachment2_[GameID]_Hand_Recording.mp4`',
        '- `Attachment3_[GameID]_latest.log`',
        '- `Attachment4_[GameID]_Hash_Result.txt` (optional; not required if already included in the email body)',
        '',
        '---',
        '',
        '### IV. Tool Usage Guide',
        '',
        '**4.1 Hash Verification Tool**',
        '- **Purpose**: Calculate the "digital fingerprint" of a file to ensure log files have not been tampered with',
        '- **Operation**: Run directly after extraction, drag `latest.log` into the window, and copy the generated string',
        '- **Note**: Do not modify any configuration files within the tool',
        '',
        '**4.2 OBS Recording Preset**',
        '- **Purpose**: Ensure recording range, frame rate, and encoder meet review standards',
        '- **Operation**: In OBS, click "Profile" → "Import" and select the official `.json` preset file',
        '- **Check**: After import, confirm that "Sources" includes "Display Capture" and "Window Capture (Hash Tool)"',
        '',
        '**4.3 FAQ**',
        '- **Q: What if the video timestamps don\'t match?**',
        '  A: Re-record. Timestamp alignment is a core review standard and cannot be fixed through post-processing.',
        '- **Q: What if the mod doesn\'t have a UI display interface?**',
        '  A: Please specify the mod name in your email, and the management side will provide an alternative or waive that provision.',
        '- **Q: Can\'t find the log file?**',
        '  A: Check if "Hide known file extensions" is enabled, or confirm whether the game successfully wrote the log.',
        '',
        '> **⚠ Important Notice**: Reviews are generally completed within 3-7 business days. Each appeal must be at least 3 days apart. After 5 consecutive appeals, each subsequent ban/kick will lower appeal priority and reduce credibility. Those who forge evidence with multiple detection records in the backend will face increased penalties and have their appeals suspended. Appeals with incomplete evidence will be rejected. Messages containing spam or insulting/threatening language will be blocked and not processed. If the content includes explicit personal attacks against the management team or other legitimate players, or threatens server security, it will not be processed, penalties will be increased, and severe cases may result in warnings or criminal proceedings.',
        '',
        '---',
        '',
        '> Final interpretation rights belong to the 4U4N Management Team. This protocol takes effect from the date of publication, and all appeals shall be based on this version.'
    ].join('\n');

    // 暴露 markdown 供文档页使用
    window.getBedwarsAppealMarkdown = function() { return appealMarkdown; };
    window.getBedwarsAppealMarkdownEn = function() { return appealMarkdownEn; };

})();
